FROM node:6.2.2

MAINTAINER KwonYoung Kim <kykim79@gmail.com>

RUN echo "Asia/Seoul" > /etc/timezone && dpkg-reconfigure -f noninteractive tzdata

RUN mkdir -p /app

COPY . app/

RUN cd /app; npm install

WORKDIR /app

VOLUME [ "/app/public/data", "app/public/image" ]

CMD npm start
